Remove Trac from our documentation
chevah/geck pull request #82
Opened 2021-11-11 17:56 UTC by adiroiban

Scope
=====

As we have migrated to GitHub, we no longer need to use Trac

Changes
=======

Convert any Trac documentation into GitHub Issues

As a drive-by I have updated the site to latest python 3.8 and sphinx version

How to try and test the changes
===============================

reviewers: @danuker 

Check that changes make sense

2021-11-11 18:46 UTC, adiroiban commented
Can you please check that the content is ok

Dan, do you have a RTD account? I can add you to the geck project and you can try to see what is going on there.


needs-review

2021-12-02 13:25 UTC, danuker commented
I created a RTD account; my login is `danuker`, but I don't seem to have a profile link. You can add me if you want.

2021-12-02 19:07 UTC, adiroiban commented
Done https://readthedocs.org/projects/chevah-geck/

2021-12-02 20:31 UTC, danuker approved these changes
Cool! Thanks for adding me to RTD. I can see the build progress now. [And the build of the last commit](https://chevah-geck--82.org.readthedocs.build/).

I have some comments, but some might be out of scope for this PR (the ones about updating the release workflow).

2021-12-02 20:33 UTC, danuker commented
changes-approved

2021-12-02 20:38 UTC, adiroiban commented on docs/product/release.rst
> +* Checking post-commit BuildBot results for the master branch (about once per week)
True.
We no longer use buildbot.
Yes. It should talk about  GitHub PR checks (GitHub Actions / Azure / Codecov ... etc).

I will update.

2021-12-02 20:39 UTC, adiroiban commented on docs/product/release.rst
>    with the master branch via RQM.
Good question.

I need the remove RQM reference.

It was migrate to a manually triggered workflow... the release process is automated, but it's manually triggered.

The release action handles the documentation and download website updates.

2021-12-02 20:42 UTC, adiroiban commented on CONTRIBUTING.rst
> +    sphinx-build -b html -j 2 -n -W docs/ build/html/
True. I will update. The output for sphinx can be any dir... but is best to use build-geck

2021-12-02 20:43 UTC, adiroiban commented on docs/product/tickets.rst
> +This may be a good ticket type to use if you are carrying out a high level task and need to keep track of notes.
yes. We should use milestones instead of story/umbrella tickets.

2022-01-10 09:40 UTC, adiroiban commented on brink.sh
> +            --trusted-host bin.chevah.com \
In terms of brink.sh is best to keep it in sync with chevah/server

2022-01-10 09:42 UTC, adiroiban commented on docs/product/tickets.rst
> +We add new tickets to the new milestone.
I don't know... we will see.

With the migration to GitHub I have to get used to use the github tools

2022-01-10 09:45 UTC, adiroiban commented on docs/programming/review.rst
> +If the PR title is `[Fix #1234] What was done in this branch` the commit message
The automatic close of tickets based on commit message is one old feature in GitHub.
Linking a ticket and a PR is another independent new feature in GitHub.

The ticket was automatically closed.

But the ticket was closed due to the commit message... which happens to be the same as the PR title :)
But the tickets are closed based on the commit message. This is a feature that is independent of PRs. You can't auto-close a ticket in GitHub with just a simple push of commit message and without using a PR.

2022-01-10 09:47 UTC, adiroiban commented
Thanks for the review.

I made some changes. Please review my responses.

This PR is about removing Trac references and not updating the whole dev and release process to GitHub tools.

The idea is that we will use GitHub only for some time, see what  works best and then extract the best practices into geck.

needs-review

Thanks!

2022-01-10 11:02 UTC, danuker commented on brink.sh
> +            --trusted-host bin.chevah.com \
So, did you intentionally move to `python2.7` for compatibility and ease of syncing from chevah/server?

2022-01-10 11:09 UTC, danuker commented on docs/product/support.rst
> +customer of the ticket ID so that they can follow up with Support on the
> and not updating the whole dev and release process to GitHub tools.

Indeed, this is scope creep. Disregard; feel free to resolve this.

2022-01-10 11:14 UTC, danuker commented on docs/programming/review.rst
> +If the PR title is `[Fix #1234] What was done in this branch` the commit message
So the reason for the syntax change to `[Fix #1234]` is to auto-close them? Since the merge commit will include the PR title?

2022-01-10 11:19 UTC, danuker requested changes
Something broke with `brink.sh` from `chevah/server`.

The other changes look fine however. Indeed, the scope of a PR should be limited.

2022-01-10 11:57 UTC, adiroiban commented on brink.sh
> +            --trusted-host bin.chevah.com \
Yep... sorry. I will revert the changes.

2022-01-10 12:00 UTC, adiroiban commented
> So the reason for the syntax change to [Fix #1234] is to auto-close them? Since the merge commit will include the PR title?
If so, resolve this conversation.

Yes. The title of the PR is automatically used as the commit message.. and the commit message can automatically close an issue :)

2022-01-10 12:20 UTC, adiroiban commented
i have reverted the brink.sh changes 

needs-review

2022-01-13 19:34 UTC, danuker approved these changes
Thanks! The site generated now.

2022-02-13 18:20 UTC, merged